title: Patrick JM # your name (or website title) here
logo: "/images/download (26).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Binusian 2023
  Binusian 2023
  Hardworking and Dilligent 
  Hardworking and Dilligent 
  <a href="https://www.linkedin.com/in/patrick-j-940b53a9/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-290494357 # your Google Analytics tracking ID here
